# Introduction to Python - Part 1

Why Python is best choice for Data Science.

* Open-source and free.
* Easy to learn.
* Fewer lines of code.
* Portability.
* Better productivity.
* Demand and popularity.
* Excellent online presence/ community.
* Support for many packages usable with analytics projects; can also use packages that can use code from other languages.
* It is faster than similar tools like R and MATLAB.
* Amazing memory management abilities.


### Things we will cover in Part 1 and 2 of Introductio to python:

* Basic Data structure

* Arithmetic Operators

* Defination of func

* loops

* numpy

* slicing

* dot T 

* random

* pandas (label, single data type for column)

* series 

* dataframe

* reindex

* loc,iloc

* sort

* null values

* merge

## Variables

###### Primitive
int, float, bool, str

In [1]:
a = 5

In [2]:
type(a)

int

In [3]:
b = 1.0

In [4]:
type(b)

float

In [5]:
s1 = 'Hello'

In [6]:
type(s1)

str

In [7]:
bol = True

In [8]:
type(bol)

bool

In [9]:
s2 = '''
Hey
you!
Hello
'''
print(s2)


Hey
you!
Hello



In [10]:
length =40

In [11]:
breadth = 30

In [12]:
area = length * breadth
print('Area = '+ str(area))
print('Area =', area)

Area = 1200
Area = 1200


Issue with these are that these store single values.

###### Non primitives : 
List [ ], Tuple ( ), Dictionary { }, Set { }

### List  : https://www.w3schools.com/python/python_lists.asp

In [13]:
lists = [1, 2, 3, 4, 5, 6]

list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

# Functions
lists_copy = lists.copy()

lists.append("orange")
lists.insert(1, "orange")
list3 = list1 + list2
print(list3)
list1.extend(list2)
print(list1)

lists.pop(0)
del lists[0]
print(lists)
lists.remove(2)
lists.clear()


['a', 'b', 'c', 1, 2, 3]
['a', 'b', 'c', 1, 2, 3]
[2, 3, 4, 5, 6, 'orange']


In [14]:
city_names = ['Pune','Mumbai','Delhi']
city_names

['Pune', 'Mumbai', 'Delhi']

### Tuple  : https://www.w3schools.com/python/python_tuples.asp

In [15]:
tuple1 = (10,20,30,40)
tuple1

(10, 20, 30, 40)

In [16]:
tuple(list1)
del tuple1

### Range: 

In [17]:
list(range(5,11))

[5, 6, 7, 8, 9, 10]

### Dictionary  : https://www.w3schools.com/python/python_dictionaries.asp

Always keep keys unique

In [18]:
dict1 = {'A':10, 'B':20, 'C':20}
dict1

{'A': 10, 'B': 20, 'C': 20}

In [19]:
dict1['A']
dict1.get('A')
for x, y in dict1.items():
    print(x,y)

dict2 = {'D':110, 'E':210}
dict1.update(dict2)
print(dict1)

dict1.pop("A")
del dict1['B']
print(dict1)
dict1.clear()

A 10
B 20
C 20
{'A': 10, 'B': 20, 'C': 20, 'D': 110, 'E': 210}
{'C': 20, 'D': 110, 'E': 210}


### Set  : https://www.w3schools.com/python/python_sets.asp

In [20]:
s1 = {'10','20','30','10'}
s1

{'10', '20', '30'}

### Loops

In [21]:
for i in range(4):
    print(i)

0
1
2
3


In [22]:
dist1 ={'A':'Alpha',
       'B':'Beta',
       'C':'Gama'}

list_dist = []
for x in dist1.items():
    list_dist.extend(list(x))
list_dist

['A', 'Alpha', 'B', 'Beta', 'C', 'Gama']

In [23]:
dist2 = {'UI1':[1,2,3],'UID2':[10,20,30]}

In [24]:
for i, j, k in dist2.values():
    print(k)

3
30


In [25]:
itr = 1
while(itr <= 5):
    print(itr)
    itr=itr+1

1
2
3
4
5


### Relations / Conditions 
!=, <=, >=, ==, <, >

In [26]:
10<20

True

In [27]:
11>20

False

In [28]:
cities = ['''Pune''','Mumbai','Nagpur']

In [29]:
if(cities[0]=='Pune'):
    print('It is raining')
else:
    print('IDK')

It is raining


In [30]:
if(cities=='Mumbai'):
    print('It is raining')
elif(cities=='Pune'):
    print('It is cold')
else:
    print('IDK')

IDK


In [31]:
for city in cities:
    if(city=='Mumbai'):
        print('It is raining')
    elif(city=='Pune'):
        print('It is cold')
    else:
        print('IDK')

It is cold
It is raining
IDK


### Functions

In [32]:
def sqr(x):
    return x*x;

In [33]:
print(sqr(10))

100


In [34]:
def adder(x,y):
    '''
    Adds x and y
    return sum
    '''
    return x+y;

In [35]:
adder(5,10)

15

### Imports

In [36]:
import math

In [37]:
math.sqrt(9)

3.0

In [38]:
import math as m

In [39]:
m.sqrt(9)

3.0

In [40]:
from math import sqrt

In [41]:
sqrt(100)

10.0

### Numpy

In [42]:
import numpy as np

In [43]:
l1= [1,2,3,4,5]
l2= [1,2,3,4,5]

arr1 = np.array(l1)
arr2 = np.array([1,2,3,4,5])

In [44]:
type(arr1)

numpy.ndarray

In [45]:
arr2

array([1, 2, 3, 4, 5])

In [46]:
l= [l1,l2]
arr3 = np.array(l)

In [47]:
# outputs (row, column)
arr3.shape

(2, 5)

In [48]:
arr3.ndim

2

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [51]:
np.arange(1,5).reshape(1,4)

array([[1, 2, 3, 4]])

In [52]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
a = np.arange(1,101).reshape(10,10)

In [55]:
a[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
 a[-1]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [57]:
a[0:5]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [58]:
a[5:]

array([[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [59]:
a[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [60]:
a[:,-5:]

array([[  6,   7,   8,   9,  10],
       [ 16,  17,  18,  19,  20],
       [ 26,  27,  28,  29,  30],
       [ 36,  37,  38,  39,  40],
       [ 46,  47,  48,  49,  50],
       [ 56,  57,  58,  59,  60],
       [ 66,  67,  68,  69,  70],
       [ 76,  77,  78,  79,  80],
       [ 86,  87,  88,  89,  90],
       [ 96,  97,  98,  99, 100]])

In [61]:
a[::2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [62]:
a[:,::2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [63]:
a[::-1]

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]])

In [64]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [65]:
# [from:to_add_1:range, from:to_add_1:range]
# [row, column]

a[6:9:2, 5:11:2]

array([[66, 68, 70],
       [86, 88, 90]])

In [66]:
  n 

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [67]:
a.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [68]:
a1 = np.arange(1,7).reshape(2,3)

In [69]:
a1+10

array([[11, 12, 13],
       [14, 15, 16]])

In [70]:
a1**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [71]:
b1 = np.arange(2,8).reshape(2,3)
b1

array([[2, 3, 4],
       [5, 6, 7]])

In [72]:
a1 + b1

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [73]:
a1 == b1

array([[False, False, False],
       [False, False, False]])

In [74]:
b1 = b1.T
b1

array([[2, 5],
       [3, 6],
       [4, 7]])

In [75]:
# (m,n) dot (n,p) = (m,p)

np.dot(a1,b1)

array([[20, 38],
       [47, 92]])

In [76]:
a1 @ b1

array([[20, 38],
       [47, 92]])

In [77]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [79]:
np.ones([10,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
c1 = np.arange(1,10)

In [82]:
np.sqrt(c1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [83]:
np.exp(c1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [84]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
        2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
        3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738],
       [3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
        3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945],
       [3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
        3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301],
       [3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
        4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456],
       [4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
        4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524],
       [4.26267988, 4.27666612, 4.2904594

In [85]:
age = np.arange(1,100)
age>60

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [86]:
age[age>60]

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [87]:
a = np.array([True, True, True])
b = np.array([True, False, True])
c = np.array([False, False, False])

In [88]:
a.any(), b.any(), c.any()

(True, True, False)

In [89]:
a.all(), b.all(), c.all()

(True, False, False)

In [90]:
# For some condition
age[age>60].all()

True