In [1]:
import numpy as np

In [2]:
#Basic 1D array
a = np.array([1,2,3])
print(a)
print(a.size)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)
print(a.astype('float64'))

[1 2 3]
3
1
(3,)
int64
8
[1. 2. 3.]


In [3]:
# Basic 2D array
b = np.array([[1.0,12.0,22.0],[11.2,21.0,1.0]])
print(b)
print(b.size)
print(b.ndim)
print(b.shape)
print(b.dtype)
print(b.itemsize)

[[ 1.  12.  22. ]
 [11.2 21.   1. ]]
6
2
(2, 3)
float64
8


In [4]:
# Get specific element  
c = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])


In [5]:
# [row, column]  
# : refers to everthing
print("Specific element:")
print(c[0,3])
print("")

Specific element:
4



In [6]:
#[startindex:endindex, startindex:endindex]
print("Full row: ")
print(c[1,:])
print("")

Full row: 
[ 7  8  9 10 11 12]



In [7]:
print("First element of all arrays:")
print(c[:,0])
print("")

First element of all arrays:
[ 1  7 13 19]



In [8]:
print("Till last element of all arrays:")
print(c[:,5])
print("")

Till last element of all arrays:
[ 6 12 18 24]



In [9]:
print("Last element of all arrays:")
print(c[:,-1])
print("")

Last element of all arrays:
[ 6 12 18 24]



In [10]:
print("Till last element of all arrays:")
print(c[:,:-1])
print("")

Till last element of all arrays:
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]



In [11]:
print("Everything except first row:")
print(c[1:,:])
print("")

Everything except first row:
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]



In [12]:
print("Everything except last row:")
print(c[:-1,:])
print("")

Everything except last row:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]



In [13]:
#[startindex:endindex:stepsize, startindex:endindex:stepsize]

In [14]:
print("Everything except last row, skipping column elements in between:")
print(c[:-1,::2])
print("")

Everything except last row, skipping column elements in between:
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]



In [15]:
#change values
c[1,5]=0
c[1,5]

print(c[:,:])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  0]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [16]:
#Revert changes
c[1,5]=12
print(c[:,:])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [17]:
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
#get 6
d[0,1,2]

6

In [19]:
#initalize array with given size with zeros
np.zeros((4,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
#initalize array with given size with ones
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
#initalize array with given size with some specified number
np.full((2,4),55)

array([[55, 55, 55, 55],
       [55, 55, 55, 55]])

In [22]:
np.full_like(b,10)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [23]:
# Random numbers
np.random.rand(2,3)

array([[0.1308674 , 0.35381259, 0.0854659 ],
       [0.51018199, 0.34843299, 0.08243016]])

In [24]:
# Random (from, to, shape)
np.random.randint(10,1000,size=(2,3))

array([[900, 267, 453],
       [525,  94, 911]])

In [25]:
# identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# repeat a number (array, timestoberepeated, axisofarray)
e = np.array([[1,2,3]])
rep = np.repeat(e,5,axis=1)
print(rep)

[[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]]


In [27]:
ex1 = np.ones((5,5))
ex2 = np.zeros((3,3))
ex1[1:-1,1:-1] = ex2
ex1[2,2] =9
ex1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# copying elements is riskyyy

f =np.array([1,2,3])
g = f
g[1] = 22
f
#so g and f are pointing to same memeory location

array([ 1, 22,  3])

In [29]:
# hence use copy function dont asign directly

f =np.array([1,2,3])
g = f.copy()
g[1] = 22
f

array([1, 2, 3])

In [30]:
# Arithmetic funtions

In [31]:
h =np.array([1,2,3,4])

print(h)
print(h+2)
print(h*2)
print(h**2)

print(h/2)
print(h+h)
print(h*h)
print(h/h)

[1 2 3 4]
[3 4 5 6]
[2 4 6 8]
[ 1  4  9 16]
[0.5 1.  1.5 2. ]
[2 4 6 8]
[ 1  4  9 16]
[1. 1. 1. 1.]


In [32]:
print(np.cos(h))
print(np.sin(h))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [33]:
#Linear algebra

In [34]:
# matrix multiplication
i = np.ones((2,3))
j = np.full((3,2),3)
print(i)
print(j)
np.matmul(i,j)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [35]:
# determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [36]:
#statistis

In [37]:
k = np.array([[5,2,4],[22,31,11]])
print(np.min(k))
print(np.max(k))
print(np.min(k,axis=1))
print(np.max(k,axis=1))
print(np.mean(k))
print(np.median(k))
print(np.sum(k))

2
31
[ 2 11]
[ 5 31]
12.5
8.0
75


In [38]:
#reorganise the array
print(k.reshape((3,2)))

[[ 5  2]
 [ 4 22]
 [31 11]]


In [39]:
l = np.array([[5,2,4],[22,31,11]])
m = np.array([[15,12,14],[122,131,111]])
print(np.vstack((l,m)))
print()
print(np.hstack((l,m)))

[[  5   2   4]
 [ 22  31  11]
 [ 15  12  14]
 [122 131 111]]

[[  5   2   4  15  12  14]
 [ 22  31  11 122 131 111]]


In [40]:
#advance indexing
n = np.array([[15,12,14],[122,131,111]])
n>100

o = n[n>100]
o

array([122, 131, 111])

In [41]:
#specify the needed element in some array by specifying th index of them 
p = np.array([15,12,14,122,131,111])
q = p[[1,2,5]]
q

array([ 12,  14, 111])

In [42]:
#give all or any elements with repect to some condition

r = np.array([[15,12,14],[122,131,111]])
print(np.any(r>50,axis=0))
print(np.all(r>50,axis=0))

[ True  True  True]
[False False False]
