## Libraries 
* Libraries are nothing but collection of modules which inturn consist of functions
* Two of the most necessary libraries that we need to be comfortable with
    * Numpy  https://numpy.org/
    * Pandas https://pandas.pydata.org/

### Numpy

In [0]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9])  # Declaring an array
array_2d = np.array([[1,2,3,4], [5,6,7,8]])  # declaring a 2d-array 
print(array)
print(array_2d)

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4]
 [5 6 7 8]]


In [0]:
# Square each element of an array
squared_array = array**2
#Advantage of using a numpy array is, we do not have to run a for loop to iterate over each element and then perform operation
print(squared_array)  

[ 1  4  9 16 25 36 49 64 81]


**Some common methods we use with a numpy array**

In [0]:
print( f'Sum of the entire array = {array.sum()}')
print( f'Minimum value in the array = {array.min()}')
print(f'Shape of the array = {array_2d.shape}' )

Sum of the entire array = 45
Minimum value in the array = 1
Shape of the array = (2, 4)


**Indexing a numpy array**

In [0]:
print(f'Third element in the array = {array[3]}')  # 3rd element. Remember, indexing starts at zero
print(f'first 3 elements of the array  = {array[0:3]}') 
print(f'last element of the array = {array[-1]}')

Third element in the array = 4
first 3 elements of the array  = [1 2 3]
last element of the array = 9


In [0]:
matrix = np.arange(1,101).reshape(10,10) # reshape such that there are 10 columns and 10 rows
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [0]:
matrix[1]    # selects the 1st row. Remember, indexing starts at 0 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [0]:
matrix[:,1]  # selects the 1st column

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [0]:
matrix[1,1]   # Selects the 1st element of the first column

12

In [0]:
x = matrix[0:2, 0:2]   # get a sub matrix from the original matrix
y = matrix[8:10, 8:10] 
print(f"Sub matrix1 = \n {x} \n\n Sub matrix2 = \n {y}")

Sub matrix1 = 
 [[ 1  2]
 [11 12]] 

 Sub matrix2 = 
 [[ 89  90]
 [ 99 100]]


In [0]:
# Boolean indexing 
matrix[matrix % 2 == 0] # selects only the even numbers

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**Arithematic operations**

In [0]:
x + y   # add two arrays. alternatively use np.add(x,y)

array([[ 90,  92],
       [110, 112]])

In [0]:
x - y   # subtract one from the other. alternatively use np.subtract(x,y)

array([[-88, -88],
       [-88, -88]])

In [0]:
x * y  # Elementwise multiplication. This is not a matrix multiplication. alternatively use np.multiply(x,y)

array([[  89,  180],
       [1089, 1200]])

In [0]:
np.power(x, 2)  # element wise power. In this case, square of each number

array([[  1,   4],
       [121, 144]], dtype=int32)

In [0]:
x.sum(axis = 0)  # row wise sum. Rows get added up

array([12, 14])

In [0]:
x.sum(axis = 1)  # column wise sum. Columns get added up

array([ 3, 23])

In [0]:
x.T    # transpose of a matrix

array([[ 1, 11],
       [ 2, 12]])

In [0]:
np.dot(x, y)   # matrix multiplication, as opposed to the element wise multiplication previously done

array([[ 287,  290],
       [2167, 2190]])

### Pandas

In [0]:
import pandas as pd

In [0]:
#Creating a Dataframe using a dictionary

dataframe = pd.DataFrame({'Name' : ['LeBron james', 'Stephen Curry', 'Chris Paul'],
                          'Team' : ['Lakers', 'Warriors', 'Thunder'],
                         'Age'   : [34,31,34]})
dataframe

Name      Team  Age
0   LeBron james    Lakers   34
1  Stephen Curry  Warriors   31
2     Chris Paul   Thunder   34

In [0]:
dataframe.index = ['Player 1', 'Player 2', 'Player 3']   # add index to the the dataframe
dataframe

Name      Team  Age
Player 1   LeBron james    Lakers   34
Player 2  Stephen Curry  Warriors   31
Player 3     Chris Paul   Thunder   34

In [0]:
df  = pd.read_csv('https://raw.githubusercontent.com/lorey/list-of-countries/master/csv/countries.csv',
                   sep = ';',        # sometimes the seperator can be different. Hence we specify that too  
                  index_col = 'name')  # set one of the columns of the dataframe as the index column
df.head()

alpha_2 alpha_3      area           capital continent  \
name                                                                         
Andorra                   AD     AND     468.0  Andorra la Vella        EU   
United Arab Emirates      AE     ARE   82880.0         Abu Dhabi        AS   
Afghanistan               AF     AFG  647500.0             Kabul        AS   
Antigua and Barbuda       AG     ATG     443.0        St. John's       NaN   
Anguilla                  AI     AIA     102.0        The Valley       NaN   

                     currency_code currency_name eqivalent_fips_code fips  \
name                                                                        
Andorra                        EUR          Euro                 NaN   AN   
United Arab Emirates           AED        Dirham                 NaN   AE   
Afghanistan                    AFN       Afghani                 NaN   AF   
Antigua and Barbuda            XCD        Dollar                 NaN   AC   
Anguilla                       XCD        Dollar                 NaN   AV   

                      geoname_id          languages         neighbours  \
name                                                                     
Andorra                  3041565                 ca              ES,FR   
United Arab Emirates      290557  ar-AE,fa,en,hi,ur              SA,OM   
Afghanistan              1149361  fa-AF,ps,uz-AF,tk  TM,CN,IR,TJ,PK,UZ   
Antigua and Barbuda      3576396              en-AG                NaN   
Anguilla                 3573511              en-AI                NaN   

                      numeric   phone  population postal_code_format  \
name                                                                   
Andorra                    20     376       84000              AD###   
United Arab Emirates      784     971     4975593                NaN   
Afghanistan                 4      93    29121286                NaN   
Antigua and Barbuda        28  +1-268       86754                NaN   
Anguilla                  660  +1-264       13254                NaN   

                     postal_code_regex  tld  
name                                         
Andorra               ^(?:AD)*(\d{3})$  .ad  
United Arab Emirates               NaN  .ae  
Afghanistan                        NaN  .af  
Antigua and Barbuda                NaN  .ag  
Anguilla                           NaN  .ai

**Indexing a Dataframe**

In [0]:
# select data based on the position
df.iloc[0:4, 0:4]   # zeroth column till the third column and zeroth row till the third row

alpha_2 alpha_3      area           capital
name                                                            
Andorra                   AD     AND     468.0  Andorra la Vella
United Arab Emirates      AE     ARE   82880.0         Abu Dhabi
Afghanistan               AF     AFG  647500.0             Kabul
Antigua and Barbuda       AG     ATG     443.0        St. John's

In [0]:
# select data based on the index label
df2.loc['India': 'Japan', 'capital':'currency_name']

capital continent currency_code  \
name                                                                   
India                              New Delhi        AS           INR   
British Indian Ocean Territory  Diego Garcia        AS           USD   
Iraq                                 Baghdad        AS           IQD   
Iran                                  Tehran        AS           IRR   
Iceland                            Reykjavik        EU           ISK   
Italy                                   Rome        EU           EUR   
Jersey                          Saint Helier        EU           GBP   
Jamaica                             Kingston       NaN           JMD   
Jordan                                 Amman        AS           JOD   
Japan                                  Tokyo        AS           JPY   

                               currency_name  
name                                          
India                                  Rupee  
British Indian Ocean Territory        Dollar  
Iraq                                   Dinar  
Iran                                    Rial  
Iceland                                Krona  
Italy                                   Euro  
Jersey                                 Pound  
Jamaica                               Dollar  
Jordan                                 Dinar  
Japan                                    Yen

In [0]:
# Select data based on index label and the position 
df.ix[10:15, 'capital':'currency_name']  # .ix[] is now depreciated. However, that is one way to subset data

C:\Users\REMYA\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


capital continent currency_code currency_name
name                                                            
American Samoa   Pago Pago        OC           USD        Dollar
Austria             Vienna        EU           EUR          Euro
Australia         Canberra        OC           AUD        Dollar
Aruba           Oranjestad       NaN           AWG       Guilder
Aland Islands    Mariehamn        EU           EUR          Euro

In [0]:
# Selecting a single column
df['area']    

name
Andorra                                      468.00
United Arab Emirates                       82880.00
Afghanistan                               647500.00
Antigua and Barbuda                          443.00
Anguilla                                     102.00
Albania                                    28748.00
Armenia                                    29800.00
Angola                                   1246700.00
Antarctica                              14000000.00
Argentina                                2766890.00
American Samoa                               199.00
Austria                                    83858.00
Australia                                7686850.00
Aruba                                        193.00
Aland Islands                               1580.00
Azerbaijan                                 86600.00
Bosnia and Herzegovina                     51129.00
Barbados                                     431.00
Bangladesh                                144000.00
Belgium

In [0]:
# Boolean indexing
df[df['area'] > 10000000]   # Select countries with area larger than 10 million sq km

alpha_2 alpha_3        area capital continent currency_code  \
name                                                                     
Antarctica      AQ     ATA  14000000.0     NaN        AN           NaN   
Russia          RU     RUS  17100000.0  Moscow        EU           RUB   

           currency_name eqivalent_fips_code fips  geoname_id  \
name                                                            
Antarctica           NaN                 NaN   AY     6697173   
Russia             Ruble                 NaN   RS     2017370   

                                                    languages  \
name                                                            
Antarctica                                                NaN   
Russia      ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua...   

                                           neighbours  numeric phone  \
name                                                                   
Antarctica                                        NaN       10   NaN   
Russia      GE,CN,BY,UA,KZ,LV,PL,EE,LT,FI,MN,NO,AZ,KP      643     7   

            population postal_code_format postal_code_regex  tld  
name                                                              
Antarctica           0                NaN               NaN  .aq  
Russia       140702000             ######         ^(\d{6})$  .ru

In [0]:
df.continent.unique()

array(['EU', 'AS', nan, 'AF', 'AN', 'SA', 'OC'], dtype=object)

In [0]:
df[df.currency_name == 'Rupee']    # Select all the countries whose currency name is "Rupee"

alpha_2 alpha_3       area     capital continent currency_code  \
name                                                                        
India           IN     IND  3287590.0   New Delhi        AS           INR   
Sri Lanka       LK     LKA    65610.0     Colombo        AS           LKR   
Mauritius       MU     MUS     2040.0  Port Louis        AF           MUR   
Nepal           NP     NPL   140800.0   Kathmandu        AS           NPR   
Pakistan        PK     PAK   803940.0   Islamabad        AS           PKR   
Seychelles      SC     SYC      455.0    Victoria        AF           SCR   

           currency_name eqivalent_fips_code fips  geoname_id  \
name                                                            
India              Rupee                 NaN   IN     1269750   
Sri Lanka          Rupee                 NaN   CE     1227603   
Mauritius          Rupee                 NaN   MP      934292   
Nepal              Rupee                 NaN   NP     1282988   
Pakistan           Rupee                 NaN   PK     1168579   
Seychelles         Rupee                 NaN   SE      241170   

                                                    languages  \
name                                                            
India       en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,s...   
Sri Lanka                                            si,ta,en   
Mauritius                                        en-MU,bho,fr   
Nepal                                                   ne,en   
Pakistan                             ur-PK,en-PK,pa,sd,ps,brh   
Seychelles                                        en-SC,fr-SC   

                   neighbours  numeric phone  population postal_code_format  \
name                                                                          
India       CN,NP,MM,BT,PK,BD      356    91  1173108018             ######   
Sri Lanka                 NaN      144    94    21513990              #####   
Mauritius                 NaN      480   230     1294104                NaN   
Nepal                   CN,IN      524   977    28951852              #####   
Pakistan          CN,AF,IR,IN      586    92   184404791              #####   
Seychelles                NaN      690   248       88340                NaN   

           postal_code_regex  tld  
name                               
India              ^(\d{6})$  .in  
Sri Lanka          ^(\d{5})$  .lk  
Mauritius                NaN  .mu  
Nepal              ^(\d{5})$  .np  
Pakistan           ^(\d{5})$  .pk  
Seychelles               NaN  .sc

**Common pandas functions**

In [0]:
#import data form external sources as a dataframe

iris = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")
iris.head()  

# .head() prints the head of the dataframe. By default, prints 5 rows. number of rows can be specidied inside the brackets

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [0]:
iris.info() 

# returns the meta data about the dataframe. number of rows & columns, data type of each column, count of columns by datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [0]:
iris.describe()  # returns the descriptive statistics of each continuous attribute

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [0]:
# adding a column to an existing dataframe
iris['id'] = range(1,151)
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  id
0           5.1          3.5           1.4          0.2  setosa   1
1           4.9          3.0           1.4          0.2  setosa   2
2           4.7          3.2           1.3          0.2  setosa   3
3           4.6          3.1           1.5          0.2  setosa   4
4           5.0          3.6           1.4          0.2  setosa   5

In [0]:
# Set an existing column as index using the set_index( ) function
iris.set_index('id', inplace = True)  # "inplace = True" means the change will be done to the original dataframe
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
id                                                              
1            5.1          3.5           1.4          0.2  setosa
2            4.9          3.0           1.4          0.2  setosa
3            4.7          3.2           1.3          0.2  setosa
4            4.6          3.1           1.5          0.2  setosa
5            5.0          3.6           1.4          0.2  setosa

In [0]:
# drop a column
iris.drop(columns= 'species')  # returns a dataframe without the column specified in the drop function

sepal_length  sepal_width  petal_length  petal_width  petal_area
id                                                                   
1             5.1          3.5           1.4          0.2        0.28
2             4.9          3.0           1.4          0.2        0.28
3             4.7          3.2           1.3          0.2        0.26
4             4.6          3.1           1.5          0.2        0.30
5             5.0          3.6           1.4          0.2        0.28
6             5.4          3.9           1.7          0.4        0.68
7             4.6          3.4           1.4          0.3        0.42
8             5.0          3.4           1.5          0.2        0.30
9             4.4          2.9           1.4          0.2        0.28
10            4.9          3.1           1.5          0.1        0.15
11            5.4          3.7           1.5          0.2        0.30
12            4.8          3.4           1.6          0.2        0.32
13            4.8          3.0           1.4          0.1        0.14
14            4.3          3.0           1.1          0.1        0.11
15            5.8          4.0           1.2          0.2        0.24
16            5.7          4.4           1.5          0.4        0.60
17            5.4          3.9           1.3          0.4        0.52
18            5.1          3.5           1.4          0.3        0.42
19            5.7          3.8           1.7          0.3        0.51
20            5.1          3.8           1.5          0.3        0.45
21            5.4          3.4           1.7          0.2        0.34
22            5.1          3.7           1.5          0.4        0.60
23            4.6          3.6           1.0          0.2        0.20
24            5.1          3.3           1.7          0.5        0.85
25            4.8          3.4           1.9          0.2        0.38
26            5.0          3.0           1.6          0.2        0.32
27            5.0          3.4           1.6          0.4        0.64
28            5.2          3.5           1.5          0.2        0.30
29            5.2          3.4           1.4          0.2        0.28
30            4.7          3.2           1.6          0.2        0.32
..            ...          ...           ...          ...         ...
121           6.9          3.2           5.7          2.3       13.11
122           5.6          2.8           4.9          2.0        9.80
123           7.7          2.8           6.7          2.0       13.40
124           6.3          2.7           4.9          1.8        8.82
125           6.7          3.3           5.7          2.1       11.97
126           7.2          3.2           6.0          1.8       10.80
127           6.2          2.8           4.8          1.8        8.64
128           6.1          3.0           4.9          1.8        8.82
129           6.4          2.8           5.6          2.1       11.76
130           7.2          3.0           5.8          1.6        9.28
131           7.4          2.8           6.1          1.9       11.59
132           7.9          3.8           6.4          2.0       12.80
133           6.4          2.8           5.6          2.2       12.32
134           6.3          2.8           5.1          1.5        7.65
135           6.1          2.6           5.6          1.4        7.84
136           7.7          3.0           6.1          2.3       14.03
137           6.3          3.4           5.6          2.4       13.44
138           6.4          3.1           5.5          1.8        9.90
139           6.0          3.0           4.8          1.8        8.64
140           6.9          3.1           5.4          2.1       11.34
141           6.7          3.1           5.6          2.4       13.44
142           6.9          3.1           5.1          2.3       11.73
143           5.8          2.7           5.1          1.9        9.69
144           6.8          3.2           5.9          2.3       13.57
145           6

**Operations of pandas dataframe**

In [0]:
# Multiply two columns
iris['petal_area'] = iris.petal_length * iris.petal_width
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  petal_area
id                                                                          
1            5.1          3.5           1.4          0.2  setosa        0.28
2            4.9          3.0           1.4          0.2  setosa        0.28
3            4.7          3.2           1.3          0.2  setosa        0.26
4            4.6          3.1           1.5          0.2  setosa        0.30
5            5.0          3.6           1.4          0.2  setosa        0.28

In [0]:
iris.drop(columns = 'petal_area', inplace = True)  # drops the column in the actual dataframe without returning anything
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
id                                                              
1            5.1          3.5           1.4          0.2  setosa
2            4.9          3.0           1.4          0.2  setosa
3            4.7          3.2           1.3          0.2  setosa
4            4.6          3.1           1.5          0.2  setosa
5            5.0          3.6           1.4          0.2  setosa

In [0]:
iris.drop(labels= [1,2,3,4])  #drops rows whose index values match with the values mentioned inside the function

sepal_length  sepal_width  petal_length  petal_width    species
id                                                                  
5             5.0          3.6           1.4          0.2     setosa
6             5.4          3.9           1.7          0.4     setosa
7             4.6          3.4           1.4          0.3     setosa
8             5.0          3.4           1.5          0.2     setosa
9             4.4          2.9           1.4          0.2     setosa
10            4.9          3.1           1.5          0.1     setosa
11            5.4          3.7           1.5          0.2     setosa
12            4.8          3.4           1.6          0.2     setosa
13            4.8          3.0           1.4          0.1     setosa
14            4.3          3.0           1.1          0.1     setosa
15            5.8          4.0           1.2          0.2     setosa
16            5.7          4.4           1.5          0.4     setosa
17            5.4          3.9           1.3          0.4     setosa
18            5.1          3.5           1.4          0.3     setosa
19            5.7          3.8           1.7          0.3     setosa
20            5.1          3.8           1.5          0.3     setosa
21            5.4          3.4           1.7          0.2     setosa
22            5.1          3.7           1.5          0.4     setosa
23            4.6          3.6           1.0          0.2     setosa
24            5.1          3.3           1.7          0.5     setosa
25            4.8          3.4           1.9          0.2     setosa
26            5.0          3.0           1.6          0.2     setosa
27            5.0          3.4           1.6          0.4     setosa
28            5.2          3.5           1.5          0.2     setosa
29            5.2          3.4           1.4          0.2     setosa
30            4.7          3.2           1.6          0.2     setosa
31            4.8          3.1           1.6          0.2     setosa
32            5.4          3.4           1.5          0.4     setosa
33            5.2          4.1           1.5          0.1     setosa
34            5.5          4.2           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
121           6.9          3.2           5.7          2.3  virginica
122           5.6          2.8           4.9          2.0  virginica
123           7.7          2.8           6.7          2.0  virginica
124           6.3          2.7           4.9          1.8  virginica
125           6.7          3.3           5.7          2.1  virginica
126           7.2          3.2           6.0          1.8  virginica
127           6.2          2.8           4.8          1.8  virginica
128           6.1          3.0           4.9          1.8  virginica
129           6.4          2.8           5.6          2.1  virginica
130           7.2          3.0           5.8          1.6  virginica
131           7.4          2.8           6.1          1.9  virginica
132           7.9          3.8           6.4          2.0  virginica
133           6.4          2.8           5.6          2.2  virginica
134           6.3          2.8           5.1          1.5  virginica
135           6.1          2.6           5.6          1.4  virginica
136           7.7          3.0           6.1          2.3  virginica
137           6.3          3.4           5.6          2.4  virginica
138           6.4          3.1           5.5          1.8  virginica
139           6.0          3.0           4.8          1.8  virginica
140           6.9          3.1           5.4          2.1  virginica
141           6.7          3.1           5.6          2.4  virginica
142           6.9          3.1           5.1          2.3  virginica
143           5.8          2.7           5.1          1.9  virginica
144           6.8          3.2           5.9          2.3  virginica
145           6.7          3.3           5.7          2.5  virginica
146

In [0]:
# Using apply function to apply a function on each element of the dataframe
iris.drop(columns='species').apply(lambda x: x*10) 
# apply a function on every element of the dataframe


sepal_length  sepal_width  petal_length  petal_width
id                                                       
1            51.0         35.0          14.0          2.0
2            49.0         30.0          14.0          2.0
3            47.0         32.0          13.0          2.0
4            46.0         31.0          15.0          2.0
5            50.0         36.0          14.0          2.0
6            54.0         39.0          17.0          4.0
7            46.0         34.0          14.0          3.0
8            50.0         34.0          15.0          2.0
9            44.0         29.0          14.0          2.0
10           49.0         31.0          15.0          1.0
11           54.0         37.0          15.0          2.0
12           48.0         34.0          16.0          2.0
13           48.0         30.0          14.0          1.0
14           43.0         30.0          11.0          1.0
15           58.0         40.0          12.0          2.0
16           57.0         44.0          15.0          4.0
17           54.0         39.0          13.0          4.0
18           51.0         35.0          14.0          3.0
19           57.0         38.0          17.0          3.0
20           51.0         38.0          15.0          3.0
21           54.0         34.0          17.0          2.0
22           51.0         37.0          15.0          4.0
23           46.0         36.0          10.0          2.0
24           51.0         33.0          17.0          5.0
25           48.0         34.0          19.0          2.0
26           50.0         30.0          16.0          2.0
27           50.0         34.0          16.0          4.0
28           52.0         35.0          15.0          2.0
29           52.0         34.0          14.0          2.0
30           47.0         32.0          16.0          2.0
..            ...          ...           ...          ...
121          69.0         32.0          57.0         23.0
122          56.0         28.0          49.0         20.0
123          77.0         28.0          67.0         20.0
124          63.0         27.0          49.0         18.0
125          67.0         33.0          57.0         21.0
126          72.0         32.0          60.0         18.0
127          62.0         28.0          48.0         18.0
128          61.0         30.0          49.0         18.0
129          64.0         28.0          56.0         21.0
130          72.0         30.0          58.0         16.0
131          74.0         28.0          61.0         19.0
132          79.0         38.0          64.0         20.0
133          64.0         28.0          56.0         22.0
134          63.0         28.0          51.0         15.0
135          61.0         26.0          56.0         14.0
136          77.0         30.0          61.0         23.0
137          63.0         34.0          56.0         24.0
138          64.0         31.0          55.0         18.0
139          60.0         30.0          48.0         18.0
140          69.0         31.0          54.0         21.0
141          67.0         31.0          56.0         24.0
142          69.0         31.0          51.0         23.0
143          58.0         27.0          51.0         19.0
144          68.0         32.0          59.0         23.0
145          67.0         33.0          57.0         25.0
146          67.0         30.0          52.0         23.0
147          63.0         25.0          50.0         19.0
148          65.0         30.0          52.0         20.0
149          62.0         34.0          54.0         23.0
150          59.0         30.0          51.0         18.0

[150 rows x 4 columns]

In [0]:
iris.species = iris.species.apply(lambda x: x.upper()) # apply a function on a particular column
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  SETOSA
1           4.9          3.0           1.4          0.2  SETOSA
2           4.7          3.2           1.3          0.2  SETOSA
3           4.6          3.1           1.5          0.2  SETOSA
4           5.0          3.6           1.4          0.2  SETOSA