# Numpy

#### 1. Create a null vector of size 15.

In [0]:
g = np.zeros(15)
print(g)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 2.  Create a null vector of size 20 but the fifth value which is 1 .

In [0]:
g = np.zeros(20)
g[4] = 1
print(g)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  Create a vector with values ranging from 11 to 45 . [Both included]

In [0]:
g = np.arange(11,46)
print(g)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45]


#### 4.  Reverse a vector (first element becomes last) values for a size of 50.

In [0]:
g = np.arange(50)
g= g[::-1]
print(g)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 5.  Create a 3x3 matrix with values ranging from 0 to 8 .[both included]

In [0]:
g = np.arange(9).reshape(3,3)
print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from \[1,2,0,0,4,0\] .

In [0]:
g = np.nonzero([1,2,0,0,4,0])
print(g)

(array([0, 1, 4], dtype=int64),)


#### 7. Create a 3x3 identity matrix .

In [0]:
g = np.eye(3)
print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 3x3x3 array with random values.

In [0]:
g = np.random.random((3,3,3))
print(g)

[[[0.4201057  0.55493867 0.20230296]
  [0.40653811 0.56209294 0.50669518]
  [0.05750532 0.61979928 0.49656729]]

 [[0.19072997 0.50389066 0.42991799]
  [0.27559193 0.40668027 0.86013253]
  [0.22559176 0.99840965 0.90475707]]

 [[0.11470782 0.17183114 0.35051629]
  [0.15622926 0.85897568 0.10976911]
  [0.97900306 0.9943739  0.44058405]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values .

In [0]:
g = np.random.random((10,10))
gmin, gmax = g.min(), g.max()
print(gmin, gmax)

0.00024130663668386898 0.9921341422235711


#### 10. Create a random vector of size 100 and find the mean value .

In [0]:
g = np.random.random(100)
m = g.mean()
print(m)

0.5922447464320082


#### 11. Create a 2d array for a size of 10 with 1 on the border and 0 inside .



In [0]:
g = np.ones((10,10))
g[1:-1,1:-1] = 0
print(g)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 12. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal .

In [0]:
g = np.diag(1+np.arange(4),k=-1)
print(g)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 13. Create a 8x8 matrix and fill it with a checkerboard pattern .

In [0]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 14. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [0]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 15. Create a checkerboard 8x8 matrix using the tile function .

In [0]:
g = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(g)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 16. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) .

In [0]:
g = np.dot(np.ones((5,3)), np.ones((3,2)))
print(g)

# Alternative solution, in Python 3.5 and above
g = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 17. Given a 1D array, negate all elements which are between 2 and 9, in place. 

In [0]:
g = np.arange(11)
g[(2 < g) & (g <= 9)] *= -1
print(g)

[ 0  1  2 -3 -4 -5 -6 -7 -8 -9 10]


#### 18. What are the result of the following expressions?

In [0]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\DILIP\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\DILIP\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 19. How to find common values between two arrays? 

In [0]:
g1 = np.random.randint(0,10,10)
g2 = np.random.randint(0,10,10)


In [0]:
print(np.intersect1d(Z1,Z2))

[2 4 5 8]


#### 20. Is the following expressions true? 

In [0]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\DILIP\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 21. How to get the dates of yesterday, today and tomorrow? 

In [0]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2019-07-28
2019-07-29
2019-07-30


#### 22. How to get all the dates corresponding to the month of July 2019? 

In [0]:
g = np.arange('2019-07', '2019-08', dtype='datetime64[D]')
print(g)

['2019-07-01' '2019-07-02' '2019-07-03' '2019-07-04' '2019-07-05'
 '2019-07-06' '2019-07-07' '2019-07-08' '2019-07-09' '2019-07-10'
 '2019-07-11' '2019-07-12' '2019-07-13' '2019-07-14' '2019-07-15'
 '2019-07-16' '2019-07-17' '2019-07-18' '2019-07-19' '2019-07-20'
 '2019-07-21' '2019-07-22' '2019-07-23' '2019-07-24' '2019-07-25'
 '2019-07-26' '2019-07-27' '2019-07-28' '2019-07-29' '2019-07-30'
 '2019-07-31']


#### 23. How to compute ((A+B)\*(-A/2)) in place (without copy)? 

In [0]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3


In [0]:
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 24. Extract the integer part of a random array using 5 different methods .

In [0]:
Z = np.random.uniform(0,10,10)



In [0]:
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[4. 1. 7. 8. 7. 5. 9. 3. 0. 7.]
[4. 1. 7. 8. 7. 5. 9. 3. 0. 7.]
[4. 1. 7. 8. 7. 5. 9. 3. 0. 7.]
[4 1 7 8 7 5 9 3 0 7]
[4. 1. 7. 8. 7. 5. 9. 3. 0. 7.]


#### 25. Create a 5x5 matrix with row values ranging from 0 to 4 .[BOTH INCLUDED]

In [0]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 26. Create a vector of size 10 with values ranging from 0 to 1, both excluded .

In [0]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 27. Create a random vector of size 10 and sort it.

In [0]:
X = np.random.random(10)
X.sort()
print(X)

[0.145271   0.18701488 0.25072629 0.50633696 0.69104983 0.69209137
 0.72749887 0.75155308 0.78738512 0.84672034]


#### 28. How to sum a small array faster than np.sum? 

In [0]:
X = np.arange(10)
np.add.reduce(X)

45

#### 29. Consider two random array A and B, check if they are equal .

In [0]:
X = np.random.randint(0,2,5)
Y = np.random.randint(0,2,5)



In [0]:
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(X,Y)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(X,Y)
print(equal)

False
False


#### 30. Make an array immutable (read-only).

In [0]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 31. Create random vector of size 20 and replace the maximum value by 0 .

In [0]:
x = np.random.random(20)
x[x.argmax()] = 0
print(x)

[0.60665626 0.68431421 0.09168047 0.1182431  0.10892111 0.31513439
 0.70953908 0.06449223 0.69513342 0.6818695  0.32966015 0.93375339
 0.65567454 0.00391669 0.70267468 0.9129046  0.65309596 0.
 0.82907189 0.23408681]


#### 32. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [0]:
x = np.arange(10, dtype=np.float32)

print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [0]:
x = x.astype(np.int32, copy=False)
print(x)

[0 1 2 3 4 5 6 7 8 9]


#### 33. What is the equivalent of enumerate for numpy arrays? 

In [0]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 34. How to randomly place p elements in a 2D array?

In [0]:
n = 10
p = 3
Z = np.zeros((n,n))

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [0]:
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 35. Subtract the mean of each row of a matrix .

In [0]:


X = np.random.rand(5, 10)



In [0]:
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)


print(Y)

[[-0.23327548 -0.4119185   0.23283312 -0.06091333  0.14658268 -0.21966496
  -0.38672643  0.35993236  0.35982587  0.21332466]
 [ 0.42766918  0.36899241 -0.30616376 -0.07878302  0.1498915   0.45241645
  -0.09070736 -0.49138052 -0.16154263 -0.27039226]
 [-0.37456255 -0.45956368  0.1340872   0.33124908  0.20615189  0.07061499
  -0.52970078 -0.04056165  0.34254761  0.31973789]
 [-0.31181959  0.29598451  0.26537053 -0.39671897 -0.32851219  0.09963458
   0.2090205   0.55257317 -0.28530298 -0.10022957]
 [ 0.20422227 -0.1150484   0.27032499  0.2382944  -0.54337744 -0.0304355
  -0.31063919  0.22057364  0.32593855 -0.25985332]]


#### 36. How to sort an array by the nth column?

In [0]:

x = np.random.randint(0,10,(3,3))
print(x)


[[4 6 2]
 [9 4 3]
 [3 2 3]]


In [0]:
print(x[x[:,1].argsort()])

[[3 2 3]
 [9 4 3]
 [4 6 2]]


#### 37. Find the nearest value from a given value in an array .

In [0]:
Z = np.random.uniform(0,1,10)


In [0]:
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.3507900517949537


#### 38. Considering a four dimensions array, how to get sum over the last two axis at once? 

In [0]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 63 48 54]
 [47 72 48 58]
 [46 31 52 55]]
[[58 63 48 54]
 [47 72 48 58]
 [46 31 52 55]]


#### 39. How to get the diagonal of a dot product? 

In [0]:


A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([2.25206171, 1.10708139, 0.47950409, 0.98778057, 1.30166188])

#### 40. Consider the vector \[1, 2, 3, 4, 5, 6\], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [0]:
Z = np.array([1,2,3,4,5,6])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0. 6.]


#### 41. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [0]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 42. How to swap two rows of an array? 

In [0]:

A = np.arange(25).reshape(5,5)

print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [0]:
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 43. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) 

In [0]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 44. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? 

In [0]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 45. Compute a matrix rank .

In [0]:
Z = np.random.uniform(0,1,(10,10))
Z

array([[0.76342281, 0.56170206, 0.8680938 , 0.21745943, 0.11242345,
        0.96130704, 0.9346674 , 0.57715482, 0.68582613, 0.59490208],
       [0.8659247 , 0.07095264, 0.64081416, 0.6574575 , 0.70470796,
        0.91661068, 0.40778221, 0.96447499, 0.69896304, 0.19070586],
       [0.17349607, 0.41526843, 0.72914443, 0.82509158, 0.74225929,
        0.96493991, 0.32462023, 0.54564237, 0.92991154, 0.33633895],
       [0.52042652, 0.60862469, 0.10774328, 0.57723606, 0.37803288,
        0.22686064, 0.49776137, 0.89411303, 0.70440815, 0.68092172],
       [0.22263664, 0.82815671, 0.85822041, 0.62113721, 0.09659524,
        0.29061155, 0.46536398, 0.69826573, 0.87038216, 0.47384195],
       [0.67044524, 0.15758447, 0.5571082 , 0.22063385, 0.5410721 ,
        0.48769564, 0.54396617, 0.31224647, 0.84775848, 0.42442524],
       [0.03041311, 0.63160515, 0.77756309, 0.30755655, 0.52119031,
        0.10418289, 0.37972605, 0.41025428, 0.91869409, 0.14956155],
       [0.91204754, 0.11118842, 0.4419122

In [0]:
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 46. How to find the most frequent value in an array?

In [0]:
Z = np.random.randint(0,10,50)
Z

array([7, 7, 4, 1, 6, 3, 9, 4, 6, 8, 9, 4, 6, 0, 8, 2, 2, 6, 3, 5, 4, 7,
       0, 9, 9, 9, 8, 8, 9, 5, 3, 2, 7, 2, 7, 3, 9, 2, 5, 5, 7, 5, 3, 0,
       0, 6, 1, 6, 4, 4])

In [0]:
print(np.bincount(Z).argmax())

9


#### 47. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

In [0]:

Z = np.ones((16,16))
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

In [0]:
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 48. How to get the n largest values of an array

In [0]:
Z = np.arange(10000)
np.random.shuffle(Z)
Z

array([ 815, 5050, 1706, ..., 7386, 9501, 4409])

In [0]:
n = 5 # How many largest numbers required.

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9996 9995 9999 9997]


# ------------------------------------ Happy Learning ---------------------------------------------